### ISSUE TITLE
In included file: too few arguments provided to function-like macro invocation

### ISSUE THREAD

**Issue by Season0518** [FeignClaims/cpp_conan_template_temp#1]
<img width="1155" alt="image" src="https://github.com/FeignClaims/cpp_conan_template/assets/30144502/0a954843-e38a-4ddf-af6a-3138afa56dc6">

After I configured gcc-13 and conan according to Configure option 2: invoice conan, then cmake, it prompted "In included file: too few arguments provided to function like macro invoice". Why is this?

OS: macOS 14.4.1 23E224 arm64

SDK:
xcode-select: version 2406
gcc: gcc-13 (Homebrew GCC 13.2.0) 13.2.0
clangd: Homebrew clangd version 18.1.5
XCode: 15.3 (SDKVersion 14.4)

**Comment by FeignClaims** [comment]
> > In fact, this problem can be easily solved through `brew upgrade gcc --greedy`.
> 
> To clarify, the issue might be caused by the update of XCode as you mentioned. Just executing `brew reinstall gcc` should be enough to solve this problem, as I did before.
> 
> I was too lazy to mention this. Sorry for the misleading.

related to Homebrew/homebrew-core#173647
